version: "3"

services:

  grafana:
    restart: always
    image: grafana/grafana-oss:8.4.3
    container_name: sa-grafana
    volumes:
      - ./grafana_data:/var/lib/grafana:rw
    ports:
      - 3000:3000
